(() => {
const SUPABASE_URL="https://ajnicsvtymvvkgepjmmk.supabase.co",KEY="sb_publishable_8DVJ4VEsYhfq2RwbbElrGw_h-RsKoWj",KEYC="rainbow_cart_v1";
const sb=window.supabase.createClient(SUPABASE_URL,KEY);const $=id=>document.getElementById(id);
const esc=x=>String(x??"").replace(/[&<>"]/g,m=>({"&":"&amp;","<":"&lt;",">":"&gt;",'"':"&quot;"}[m]));
const money=x=>"₹"+Number(x||0).toLocaleString("en-IN",{minimumFractionDigits:2,maximumFractionDigits:2});
let cart=[];let delivery=0;
function read(){try{cart=JSON.parse(localStorage.getItem(KEYC)||"[]")}catch{cart=[]}updateCount()}
function save(){localStorage.setItem(KEYC,JSON.stringify(cart));updateCount()}
function updateCount(){$("cartCount").textContent=cart.reduce((n,x)=>n+Number(x.quantity||0),0)}
function totals(){const sub=cart.reduce((n,x)=>n+Number(x.product.selling_price||0)*x.quantity,0);const disc=Math.round(sub*.03*100)/100;const taxable=sub-disc;const cgst=Math.round(taxable*.015*100)/100;const sgst=Math.round(taxable*.015*100)/100;const total=Math.round((taxable+cgst+sgst+delivery)*100)/100;$("subtotal").textContent=money(sub);$("discount").textContent=money(disc);$("cgst").textContent=money(cgst);$("sgst").textContent=money(sgst);$("delivery").textContent=delivery?money(delivery):"Calculated by store";$("total").textContent=money(total);return{sub,disc,cgst,sgst,total}}
function render(){if(!cart.length){$("orderItems").innerHTML='<div class="empty">Your cart is empty. <a href="index.html#products">Browse products →</a></div>';$("placeOrder").disabled=true;totals();return} $("placeOrder").disabled=false;$("orderItems").innerHTML=cart.map((x,i)=>'<div class="order-item">'+(x.product.image?'<img src="'+esc(x.product.image)+'" alt="">':'<div class="order-item-placeholder"></div>')+'<div><h3>'+esc(x.product.product_name)+'</h3><small>'+esc(x.product.product_code)+' • '+money(x.product.selling_price)+'</small><div class="order-qty"><button data-dec="'+i+'">−</button><span>'+x.quantity+'</span><button data-inc="'+i+'">＋</button></div></div><div class="order-price">'+money(Number(x.product.selling_price)*x.quantity)+'</div></div>').join("");document.querySelectorAll("[data-inc]").forEach(b=>b.onclick=()=>change(+b.dataset.inc,1));document.querySelectorAll("[data-dec]").forEach(b=>b.onclick=()=>change(+b.dataset.dec,-1));totals()}
function change(i,d){cart[i].quantity=Math.max(1,cart[i].quantity+d);save();render()}
function msg(s,c=""){$("orderMsg").textContent=s;$("orderMsg").className="order-msg "+c}
$("clearCart").onclick=()=>{cart=[];save();render()};$("distance").oninput=()=>{delivery=0;totals()};
$("placeOrder").onclick=async()=>{if(!cart.length)return;const customer={name:$("name").value.trim(),whatsapp_number:$("phone").value.trim(),email:$("email").value.trim(),pin_code:$("pin").value.trim(),city:$("city").value.trim(),state:$("state").value.trim(),address:$("address").value.trim()};if(!customer.name||!customer.whatsapp_number||!customer.address){msg("Name, WhatsApp number and delivery address are required.","error");return}const distance=$("distance").value?Number($("distance").value):null;msg("Placing your order…");$("placeOrder").disabled=true;try{const {data,error}=await sb.rpc("create_online_order",{p_items:cart.map(x=>({variant_id:x.variant_id,quantity:x.quantity})),p_customer:customer,p_delivery_distance_km:distance});if(error)throw error;cart=[];save();$("orderLayout").hidden=true;$("orderSuccess").hidden=false;$("orderSuccess").innerHTML='<h2>Order received.</h2><p>Your order number is <strong>'+esc(data.order_number)+'</strong>.</p><p>Total: <strong>'+money(data.total_amount)+'</strong>. Rainbow Gold Covering will contact you on WhatsApp to confirm the order and delivery details.</p><a class="btn btn-dark" href="index.html#products">Continue Shopping</a>';}catch(e){console.error(e);msg(e.message||"We could not place the order. Please try again.","error");$("placeOrder").disabled=false}};
read();render();
})();