let inventoryRules=null;
async function getInventoryRules(){if(!inventoryRules)inventoryRules=await import("../src/domain/inventoryRules.mjs");return inventoryRules;}

let inventory=[],categories=[],selectedCategoryId=null;
async function loadInventory(){inventoryRules=await getInventoryRules();categories=await sb("categories?select=id,name,has_color,has_size,has_length,has_thickness,has_gold_amount&active=eq.true&order=name");inventory=await sb("product_variants?select=id,color,size,stock_quantity,low_stock_limit,barcode,products(id,product_code,product_name,type,category_id,length_cm,thickness,gold_amount_g)&active=eq.true&order=created_at.desc");if(categories.length)selectedCategoryId=selectedCategoryId||categories[0].id;renderCategories();renderInventory();}
function renderCategories(){document.getElementById("categoryTabs").innerHTML=categories.map(c=>'<button type="button" class="'+(c.id===selectedCategoryId?"active":"")+'" data-id="'+c.id+'">'+c.name+'</button>').join("");document.querySelectorAll("#categoryTabs button").forEach(b=>b.onclick=()=>{selectedCategoryId=b.dataset.id;renderCategories();renderInventory();});}
function status(v){const s=inventoryRules.getStockStatus(v.stock_quantity,v.low_stock_limit);return[s.label,s.tone];}
function esc(x){return String(x??"").replace(/[&<>"]/g,m=>({"&":"&amp;","<":"&lt;",">":"&gt;",'"':"&quot;"}[m]));}
function renderInventory(){const cat=categories.find(c=>c.id===selectedCategoryId);if(!cat)return;const q=(document.getElementById("search").value||"").toLowerCase().trim();const rows=inventory.filter(v=>{const p=v.products||{};return p.category_id===selectedCategoryId&&[p.product_code,p.product_name,p.type,v.color,v.size,v.barcode].some(x=>String(x??"").toLowerCase().includes(q));});document.getElementById("selectedCategory").textContent=cat.name;document.getElementById("categoryMeta").textContent=rows.length+" product variants";document.getElementById("variantCount").textContent=rows.length;document.getElementById("stockCount").textContent=rows.reduce((s,v)=>s+Number(v.stock_quantity||0),0);document.getElementById("lowCount").textContent=rows.filter(v=>Number(v.stock_quantity||0)>0&&Number(v.stock_quantity||0)<=Number(v.low_stock_limit||0)).length;document.getElementById("outCount").textContent=rows.filter(v=>Number(v.stock_quantity||0)===0).length;
let columns=["Code","Product","Type"];if(cat.has_color)columns.push("Color");if(cat.has_size)columns.push("Size");if(cat.has_length)columns.push("Length");if(cat.has_thickness)columns.push("Thickness");if(cat.has_gold_amount)columns.push("Gold Amount");columns.push("Stock","Limit","Status","Barcode");document.getElementById("head").innerHTML="<tr>"+columns.map(x=>"<th>"+x+"</th>").join("")+"</tr>";
document.getElementById("rows").innerHTML=rows.map(v=>{const p=v.products||{},[label,cls]=status(v);let cells="<td><b>"+esc(p.product_code||"—")+"</b></td><td>"+esc(p.product_name||"—")+"</td><td>"+esc(p.type||"—")+"</td>";if(cat.has_color)cells+="<td>"+esc(v.color||"0")+"</td>";if(cat.has_size)cells+="<td>"+esc(v.size||"0")+"</td>";if(cat.has_length)cells+="<td>"+(p.length_cm==null?"—":esc(p.length_cm)+" cm")+"</td>";if(cat.has_thickness)cells+="<td>"+esc(p.thickness||"—")+"</td>";if(cat.has_gold_amount)cells+="<td>"+(p.gold_amount_g==null?"—":esc(p.gold_amount_g)+" g")+"</td>";cells+="<td><b>"+Number(v.stock_quantity||0)+"</b></td><td>"+Number(v.low_stock_limit||0)+"</td><td><span class='"+cls+"'>"+label+"</span></td><td>"+esc(v.barcode||"—")+"</td>";return"<tr>"+cells+"</tr>"}).join("")||"<tr><td colspan='"+columns.length+"'>No products found in this category.</td></tr>";}
document.getElementById("search").oninput=renderInventory;if(document.getElementById("rows"))requireSession().then(loadInventory).catch(console.error);