const STAFF_URL=SUPABASE_URL+"/functions/v1/create-staff-user";
function escapeHtml(v){return String(v??"").replace(/[&<>"']/g,m=>({"&":"&amp;","<":"&lt;",">":"&gt;",'"':"&quot;","'":"&#039;"}[m]));}
function showStaffError(message){const rows=document.querySelector("#staffRows");if(rows)rows.innerHTML="<tr><td colspan='5' style='color:#b42318'>"+escapeHtml(message)+"</td></tr>";const msg=document.querySelector("#formMsg");if(msg){msg.textContent=message;msg.className="form-msg error";}}
async function adminGuard(){const p=await getMyProfile();if(!p.active||p.role!=="admin"){document.body.innerHTML="<main style='margin:0;padding:60px'><h1>Access denied</h1><p>Only an active admin can manage staff.</p><button onclick=\"location.href='index.html'\">Back to dashboard</button></main>";throw new Error("Admin access required.");}return p;}
async function loadStaff(){try{const {data,error}=await bootSupabase().from("staff_profiles").select("user_id,full_name,username,role,active,created_at").order("created_at",{ascending:true});if(error)throw new Error(error.message);document.querySelector("#staffRows").innerHTML=(data||[]).map(s=>`<tr><td><b>${escapeHtml(s.full_name||"—")}</b></td><td class="muted">${escapeHtml(s.username||"—")}</td><td><select onchange="changeRole('${s.user_id}',this.value)" ${s.role==="admin"?"disabled":""}><option value="cashier" ${s.role==="cashier"?"selected":""}>Cashier</option><option value="inventory_staff" ${s.role==="inventory_staff"?"selected":""}>Inventory Staff</option></select></td><td><span class="status ${s.active?"status-on":"status-off"}">${s.active?"Active":"Inactive"}</span></td><td>${s.role==="admin"?"<span class='muted'>Protected</span>":"<button onclick=\"toggleStaff('"+s.user_id+"',"+(!s.active)+")\">"+(s.active?"Deactivate":"Activate")+"</button>"}</td></tr>`).join("")||"<tr><td colspan='5'>No staff yet.</td></tr>";}catch(e){showStaffError("Could not load staff: "+e.message);console.error(e);}}
async function createStaff(e){e.preventDefault();const msg=document.querySelector("#formMsg");msg.textContent="Creating staff…";msg.className="form-msg";try{const session=await requireSession();const r=await fetch(STAFF_URL,{method:"POST",headers:{Authorization:"Bearer "+session.access_token,apikey:SUPABASE_ANON_KEY,"Content-Type":"application/json"},body:JSON.stringify({name:document.querySelector("#name").value.trim(),username:document.querySelector("#username").value.trim().toLowerCase(),password:document.querySelector("#password").value,role:document.querySelector("#role").value})});const text=await r.text();let data={};try{data=JSON.parse(text)}catch{}if(!r.ok)throw new Error(data.error||text||("Could not create staff ("+r.status+")."));msg.textContent="Staff created. They can log in with the username and password.";msg.className="form-msg success";document.querySelector("#staffForm").reset();await loadStaff();}catch(e){msg.textContent=e.message;msg.className="form-msg error";console.error(e);}}
async function changeRole(userId,role){try{const {error}=await bootSupabase().from("staff_profiles").update({role}).eq("user_id",userId);if(error)throw new Error(error.message);await loadStaff();}catch(e){alert(e.message);await loadStaff();}}
async function toggleStaff(userId,active){if(!confirm(active?"Activate this staff account?":"Deactivate this staff account?"))return;try{const {error}=await bootSupabase().from("staff_profiles").update({active}).eq("user_id",userId);if(error)throw new Error(error.message);await loadStaff();}catch(e){alert(e.message);}}
async function bootStaff(){try{document.querySelector("#staffForm").addEventListener("submit",createStaff);await adminGuard();await loadStaff();}catch(e){showStaffError(e.message);console.error(e);}}
if(document.readyState==="loading")document.addEventListener("DOMContentLoaded",bootStaff,{once:true});else bootStaff();